language: c
sudo: false

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
   - arduino --board arduino:avr:uno

script:
   - build_platform uno
